Add spring-data sample with Kotlin
spring-projects/spring-aot-smoke-tests pull request #125
Opened 2022-10-18 14:06 UTC by christophstrobl

Add a copy of the `data-jpa` sample using _Kotlin_ to verify the specific reflection needs when using _Kotlin_ (see: spring-projects/spring-data-commons#2717)

Note: This sample will fail till the issue in `data-commons` is resolved.

2022-10-18 14:16 UTC, mhalbritter requested changes

2022-10-18 14:16 UTC, mhalbritter commented on data-jpa-kotlin/src/main/kotlin/com/example/data/jpa/kotlin/AutorRepository.kt
> +	fun findByNameContainingIgnoreCase(partialName: String?): Optional<Author?>?
A nullable `Optional` doesn't seem right. Maybe just `Author?`?

2022-10-18 14:16 UTC, mhalbritter commented on data-jpa-kotlin/src/main/kotlin/com/example/data/jpa/kotlin/AutorRepository.kt
> +interface AuthorRepository : JpaRepository<Author?, Long?> {
`<Author?, Long?>`: can that be `<Author, Long>`?

2022-10-18 14:16 UTC, mhalbritter commented on data-jpa-kotlin/src/main/kotlin/com/example/data/jpa/kotlin/AutorRepository.kt
> +	fun queryFindByName(name: String?): Optional<Author?>?
I think the `name` shouldn't be nullable here.

2022-10-18 14:16 UTC, mhalbritter commented on data-jpa-kotlin/src/main/kotlin/com/example/data/jpa/kotlin/model/Autor.kt
> +	var books: Set<Book>? = null
Make it non-nullable and assign `emptySet` to it? Does that work with JPA?

2022-10-18 21:00 UTC, sdeleuze requested changes
Please add a JPA callback like `@PreRemove` to test spring-projects/spring-framework#29348 with Kotlin.

2022-10-19 08:30 UTC, christophstrobl commented
@mhalbritter applied some changes

2022-10-24 12:18 UTC, merged

2022-10-24 12:18 UTC, mhalbritter commented
Thanks, going to polish it.