Add session-jdbc-security sample
spring-projects/spring-aot-smoke-tests pull request #77
Opened 2022-08-04 14:34 UTC by marcusdacoregio

Closes gh-27

2022-08-05 07:03 UTC, mhalbritter requested changes

2022-08-05 07:03 UTC, mhalbritter commented on session-jdbc-security/README.md
> +Tests the session persistence and cookie customization from Spring Session together with Spring Session JDBC and Spring Security.
I don't quite get why this smoke test has Security in it. Is there something in session / security which has to be tested in combination? If not, I would be in favor of removing security from that smoke test.

2022-08-05 07:03 UTC, mhalbritter commented on session-jdbc-security/src/main/java/com/example/session/MainController.java
> +		return "home";
If we're not needing Security, you can remove that controller.

2022-08-05 07:04 UTC, mhalbritter commented
Hey @marcusdacoregio thanks for the sample. I have added some remarks, please take a look at them.

2022-08-05 17:02 UTC, marcusdacoregio commented
Hi @mhalbritter, thanks for the review. The PR is now updated.

2022-08-08 06:30 UTC, merged

2022-08-08 06:31 UTC, mhalbritter commented
Merged, thanks a lot @marcusdacoregio !